### ISSUE TITLE
BrokenPipeError and EOFError when running training loop

### ISSUE THREAD

**Issue by framepixel** [aai-institute/tianshou#911] opened 2023-08-12 14:38 UTC
- [x] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, gymnasium as gym, torch, numpy, sys
  print(tianshou.__version__, gym.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  0.4.11 0.28.1 2.0.1 1.24.4 3.9.16 (main, Mar  8 2023, 10:39:24) [MSC v.1916 64 bit (AMD64)] win32
  ```
So, I am new to Tianshou, and I have been trying to run my training loop, but I always end up getting this exception:

```python
Traceback (most recent call last):
  File "c:\Users\aylam\.conda\envs\rllbc_bpa2\lib\multiprocessing\connection.py", line 312, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
BrokenPipeError: [WinError 109] The pipe has been ended

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\aylam\AppData\Local\Temp\ipykernel_13464\1679833143.py", line 3, in <module>
    result = offpolicy_trainer(
  File "C:\Users\aylam\AppData\Roaming\Python\Python39\site-packages\tianshou\trainer\offpolicy.py", line 133, in offpolicy_trainer
    return OffpolicyTrainer(*args, **kwargs).run()
  File "C:\Users\aylam\AppData\Roaming\Python\Python39\site-packages\tianshou\trainer\base.py", line 441, in run
    deque(self, maxlen=0)  # feed the entire iterator into a zero-length deque
  File "C:\Users\aylam\AppData\Roaming\Python\Python39\site-packages\tianshou\trainer\base.py", line 252, in __iter__
    self.reset()
  File "C:\Users\aylam\AppData\Roaming\Python\Python39\site-packages\tianshou\trainer\base.py", line 237, in reset
    test_result = test_episode(
  File "C:\Users\aylam\AppData\Roaming\Python\Python39\site-packages\tianshou\trainer\utils.py", line 27, in test_episode
    result = collector.collect(n_episode=n_episode)
  File "C:\Users\aylam\AppData\Roaming\Python\Python39\site-packages\tianshou\data\collector.py", line 314, in collect
    result = self.env.step(action_remap, ready_env_ids)  # type: ignore
  File "C:\Users\aylam\AppData\Roaming\Python\Python39\site-packages\tianshou\env\venvs.py", line 287, in step
    env_return = self.workers[j].recv()
  File "C:\Users\aylam\AppData\Roaming\Python\Python39\site-packages\tianshou\env\worker\subproc.py", line 219, in recv
...
    buf = self._recv_bytes()
  File "c:\Users\aylam\.conda\envs\rllbc_bpa2\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError
```

Here is the environment constructor and reset function:
```py
class TradingEnv(gym.Env):
    def __init__(self, data, simplified=True, render_mode=None, currency_change_interval=10):
        self.render_mode = render_mode
        self.dataframes = data  # Dictionary of dataframes (name -> dataframe) for different currencies
        self.crypto_names = list(self.dataframes.keys())
        self.current_crypto_name = self.crypto_names[0]  # Start with the first cryptocurrency
        self.current_dataframe = self.dataframes[self.current_crypto_name]
        self.current_dataframe_index = 0

        self.simplified = simplified
        self.action_space = spaces.Discrete(3) # buy, sell, hold
        self.last_buy, self.last_sell = None, None

        # Define the lower and upper bounds for the float values
        float_low = -100.0
        float_high = 100.0

        # Define the lower and upper bounds for the volume
        volume_low = 0.0
        volume_high = 10000.0

        if simplified:
            # self.observation_space = spaces.Box(low=0, high=1, shape=(9,))
            # Define the observation space
            self.observation_space = spaces.Box(
                low=np.array([
                    0, float_low, float_low, float_low, float_low, volume_low,
                    float_low, 0, 0 #, float_low, -1, -1, float_low, float_low
                ]),
                high=np.array([
                    1767232000000, float_high, float_high, float_high, float_high, volume_high,
                    float_high, 1, 1 #, float_high, 1, 1, float_high, float_high
                ]),
                dtype=np.float32
            )
        self.current_step = None
        self.reward_range = (-1, 1)
        self.currency_change_interval = currency_change_interval
        self.episode_counter = 0
```
```py
def reset(self, seed=None, options=None):
    self.current_step = 0
    self.episode_counter += 1

    if self.episode_counter % self.currency_change_interval == 0:
        self.current_dataframe_index = (self.current_dataframe_index + 1) % len(self.dataframes)
        self.current_dataframe = self.dataframes[self.current_dataframe_index]

    self.last_buy, self.last_sell = None, None

    return self._next_observation()
```
And here is the main code:
```py
from TradingEnv_Tianshou import TradingEnv as TRT
env = TRT(dataframes) # dataframes is a dictionary which contains a string as key, and a dataframe as value

train_envs = SubprocVectorEnv([lambda: TRT(dataframes) for _ in range(1)])
test_envs = SubprocVectorEnv([lambda: TRT(test_dataframes) for _ in range(1)])

state_shape = env.observation_space.shape or env.observation_space.n
action_shape = env.action_space.shape or env.action_space.n
net = Net(state_shape[0], action_shape)
optim = torch.optim.Adam(net.parameters(), lr=1e-3)
policy = DQNPolicy(net, optim, discount_factor=0.9, estimation_step=3)

train_collector = Collector(policy, train_envs, VectorReplayBuffer(total_size=1000000, buffer_num=4))
test_collector = Collector(policy, test_envs)

result = offpolicy_trainer(
    policy, train_collector, test_collector,
    max_epoch=20, step_per_epoch=3000, 
    episode_per_test=2, batch_size=64, step_per_collect=10,
    train_fn=lambda epoch, env_step: policy.set_eps(0.1),
    test_fn=lambda epoch, env_step: policy.set_eps(0.05),
    stop_fn = lambda mean_rewards: env.spec is not None and env.spec.reward_threshold is not None and mean_rewards >= env.spec.reward_threshold,
)
```

**Comment by Trinkle23897** [comment] 2023-08-12 15:56
Could you try replacing trading env with normal gymnasium env? If there’s still raising error, the issue is library code; otherwise the issue is inside env code.

**Comment by framepixel** [comment] 2023-08-12 16:24
I tried using CartPole, and it does work. What could be causing this error in my custom environment?

**Comment by Trinkle23897** [comment] 2023-08-12 18:30
You need to return two objects instead of one in reset function, it's (obs, info)

**Comment by framepixel** [comment] 2023-08-12 18:53
my `_next_observation` function looked like this:
```py
def _next_observation(self):
        if self.simplified:
            obs = np.array([
                self.current_dataframe.iloc[self.current_step].loc[ 'time'],
                self.current_dataframe.iloc[self.current_step].loc[ 'open'] / 1000,
                self.current_dataframe.iloc[self.current_step].loc[ 'high'] / 1000,
                self.current_dataframe.iloc[self.current_step].loc[ 'low'] / 1000,
                self.current_dataframe.iloc[self.current_step].loc[ 'close'] / 1000,
                self.current_dataframe.iloc[self.current_step].loc[ 'volume'],
                self.current_dataframe.iloc[self.current_step].loc[ 'zlsma'] / 1000,
                self.current_dataframe.iloc[self.current_step].loc[ 'buy_signal'],
                self.current_dataframe.iloc[self.current_step].loc[ 'sell_signal'],
            ])
        return obs, {}
```
and reset would return this:
```py
return self._next_observation()
```
Now I turned it into this:
```py
def _next_observation(self):
        if self.simplified:
            obs = np.array([
                self.current_dataframe.iloc[self.current_step].loc[ 'time'],
                self.current_dataframe.iloc[self.current_step].loc[ 'open'] / 1000,
                self.current_dataframe.iloc[self.current_step].loc[ 'high'] / 1000,
                self.current_dataframe.iloc[self.current_step].loc[ 'low'] / 1000,
                self.current_dataframe.iloc[self.current_step].loc[ 'close'] / 1000,
                self.current_dataframe.iloc[self.current_step].loc[ 'volume'],
                self.current_dataframe.iloc[self.current_step].loc[ 'zlsma'] / 1000,
                self.current_dataframe.iloc[self.current_step].loc[ 'buy_signal'],
                self.current_dataframe.iloc[self.current_step].loc[ 'sell_signal'],
            ])
        return obs
```
and reset returns now:
```py
return self._next_observation(), {}
```
But I still get the same error.

**Comment by MischaPanch** [comment] 2023-08-16 19:10
Seems like your error is raised in step and not in reset. I would start looking there, you need to comply with gymnasium's interface. Without further info, my bet is that you are manipulating some global object there which causes problems in the multiprocessing parallelized rollout

(it wouldn't go to call `env.step` if reset had failed before)
```
  File "C:\Users\aylam\AppData\Roaming\Python\Python39\site-packages\tianshou\data\collector.py", line 314, in collect
    result = self.env.step(action_remap, ready_env_ids)  # type: ignore
```

**Comment by framepixel** [comment] 2023-08-26 08:49
I checked to see if there is something wrong with the `step` method, but it does comply with the gymnasium interface. 
Here is the `step` function.

```py
    def step(self, action):
        self.current_step += 1
        obs, info = self._next_observation()
        done = False
        reward = 0

        if action == 0:  
            reward = self.current_dataframe.iloc[self.current_step].loc['close'] / self.last_sell - 1
            self.last_buy = self.current_dataframe.iloc[self.current_step].loc['close']
        elif action == 1: 
            reward = self.current_dataframe.iloc[self.current_step].loc['close'] / self.last_buy - 1
            self.last_sell = self.current_dataframe.iloc[self.current_step].loc['close']
            
        if self.current_step == len(self.df) - 1:
            done = True
            
        return obs, reward, done, False, info
```

**Comment by MischaPanch** [comment] 2023-09-03 22:33
Since it worked on a gym env, it doesn't seem like a tianshou issue. I'm closing this.

Can't really say what's going on here, might be some problem of global state shared in multiple processes (if you refer to some fixed dict or a stream in your env).

**Closed as completed** 2023-09-03 22:33 UTC
