### ISSUE TITLE
EOFError on training

### ISSUE THREAD

**Issue by HYB777** [aai-institute/tianshou#1184] opened 2024-08-01 18:36 UTC
Hello, I meet the EOFError during the training, and I don't have any clue about it.

Here is the exception:

> Traceback (most recent call last):
  File "/home/hyb/hyb/ShapeOptDemos/shape-rl/rl-project/main.py", line 511, in <module>
    main(get_args())
  File "/home/hyb/hyb/ShapeOptDemos/shape-rl/rl-project/main.py", line 388, in main
    result = offpolicy_trainer(
  File "/home/hyb/anaconda3/envs/hyb/lib/python3.9/site-packages/tianshou/trainer/offpolicy.py", line 133, in offpolicy_trainer
    return OffpolicyTrainer(*args, **kwargs).run()
  File "/home/hyb/anaconda3/envs/hyb/lib/python3.9/site-packages/tianshou/trainer/base.py", line 441, in run
    deque(self, maxlen=0)  # feed the entire iterator into a zero-length deque
  File "/home/hyb/anaconda3/envs/hyb/lib/python3.9/site-packages/tianshou/trainer/base.py", line 288, in __next__
    data, result, self.stop_fn_flag = self.train_step()
  File "/home/hyb/anaconda3/envs/hyb/lib/python3.9/site-packages/tianshou/trainer/base.py", line 384, in train_step
    result = self.train_collector.collect(
  File "/home/hyb/anaconda3/envs/hyb/lib/python3.9/site-packages/tianshou/data/collector.py", line 295, in collect
    obs_next, rew, terminated, truncated, info = self.env.step(
  File "/home/hyb/anaconda3/envs/hyb/lib/python3.9/site-packages/tianshou/env/venvs.py", line 348, in step
    env_return = self.workers[j].recv()
  File "/home/hyb/anaconda3/envs/hyb/lib/python3.9/site-packages/tianshou/env/worker/subproc.py", line 204, in recv
    result = self.parent_remote.recv()
  File "/home/hyb/anaconda3/envs/hyb/lib/python3.9/multiprocessing/connection.py", line 255, in recv
    buf = self._recv_bytes()
  File "/home/hyb/anaconda3/envs/hyb/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/home/hyb/anaconda3/envs/hyb/lib/python3.9/multiprocessing/connection.py", line 388, in _recv
    raise EOFError
EOFError

**Comment by MischaPanch** [comment] 2024-08-02 19:55
What did you run? Seems like you're using python 3.9, which is not supported. Do you use an old version of tianshou?

**Comment by HYB777** [comment] 2024-08-02 19:58
> What did you run? Seems like you're using python 3.9, which is not supported. Do you use an old version of tianshou?

Yes, I'm using python3.9, and the version of tianshou is 0.5.0

**Comment by MischaPanch** [comment] 2024-08-02 20:01
This is a very old version, I can't help you there, sry :).

If possible for you, I suggest that you use python 3.11 and the version from master. You can also use the released 1.0.0, but master has several more features. We will release 1.1.0 soon

**Comment by HYB777** [comment] 2024-08-04 02:51
> This is a very old version, I can't help you there, sry :).
> 
> If possible for you, I suggest that you use python 3.11 and the version from master. You can also use the released 1.0.0, but master has several more features. We will release 1.1.0 soon

I take your advice and use the latest released version (python 3.11 + tianshou 1.0.0), but still have the same problem, here is the exception:

> Traceback (most recent call last):
  File "/home/hyb/hyb/ShapeOptDemos/shape-rl/rl-project-ts/main.py", line 510, in <module>
    main(get_args())
  File "/home/hyb/hyb/ShapeOptDemos/shape-rl/rl-project-ts/main.py", line 403, in main
    ).run()
      ^^^^^
  File "/home/hyb/anaconda3/envs/ts/lib/python3.11/site-packages/tianshou/trainer/base.py", line 526, in run
    deque(self, maxlen=0)  # feed the entire iterator into a zero-length deque
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyb/anaconda3/envs/ts/lib/python3.11/site-packages/tianshou/trainer/base.py", line 314, in __next__
    train_stat, self.stop_fn_flag = self.train_step()
                                    ^^^^^^^^^^^^^^^^^
  File "/home/hyb/anaconda3/envs/ts/lib/python3.11/site-packages/tianshou/trainer/base.py", line 436, in train_step
    result = self.train_collector.collect(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyb/anaconda3/envs/ts/lib/python3.11/site-packages/tianshou/data/collector.py", line 317, in collect
    obs_next, rew, terminated, truncated, info = self.env.step(
                                                 ^^^^^^^^^^^^^^
  File "/home/hyb/anaconda3/envs/ts/lib/python3.11/site-packages/tianshou/env/venvs.py", line 279, in step
    env_return = self.workers[j].recv()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyb/anaconda3/envs/ts/lib/python3.11/site-packages/tianshou/env/worker/subproc.py", line 224, in recv
    result = self.parent_remote.recv()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyb/anaconda3/envs/ts/lib/python3.11/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "/home/hyb/anaconda3/envs/ts/lib/python3.11/multiprocessing/connection.py", line 430, in _recv_bytes
    buf = self._recv(4)
          ^^^^^^^^^^^^^
  File "/home/hyb/anaconda3/envs/ts/lib/python3.11/multiprocessing/connection.py", line 399, in _recv
    raise EOFError
EOFError

**Comment by MischaPanch** [comment] 2024-08-04 14:17
Ok, I can look into it. But I still need some code to execute such that I can reproduce the problem. What are you executing? Does running the example scripts work?

This could be caused by summer environment internals falling, which is not on tianshou. For debugging, you should run the experiment with a single environment

**Comment by MischaPanch** [comment] 2024-08-05 09:44
@HYB777 The EOF error just indicates that something went wrong, it's an error from multiprocessing. For debugging, you can set the number of train envs to 1 and use the `dummy` vector env

**Comment by HYB777** [comment] 2024-08-05 11:32
> @HYB777 The EOF error just indicates that something went wrong, it's an error from multiprocessing. For debugging, you can set the number of train envs to 1 and use the `dummy` vector env

Thanks for your advice, I'll try it.

**Comment by MischaPanch** [comment] 2024-08-06 11:58
Resolving this since the issue description doesn't allow to do anything about it. @HYB777 if you find that the error is indeed caused by tianshou, feel free to open a new issue with a description on how to reproduce it

**Closed as completed by MischaPanch** 2024-08-06 11:58 UTC
Labels: question
